### ISSUE TITLE
this is SICK, but it's for crosswords more than scrabble

### ISSUE THREAD

**Issue by rub1e** [jmnr/scrabble#7]
if you wanted to make it scrabble useful, you could have another box where you enter your tiles and it only searches for words that contain the anchor letters and your spare tiles (does that make sense?!)

**Comment by joshpitzalis** [comment]
we are changing the name for now. Can work on adding that it if we decide to revisit the project at some point in the future

**Comment by msmichellegar** [comment]
Rebranded! Introducing CR_SSW_RD.
